import { NextRequest, NextResponse } from "next/server";
import { verifyAdminToken, unauthorizedResponse } from "@/lib/adminAuth";
import { supabaseAdmin } from "@/lib/supabase";
import { resend, FROM_EMAIL, qrTicketHtml } from "@/lib/resend";
import { getEvent } from "@/lib/events";
import { TICKET_LABELS } from "@/lib/stripe";

// Resend QR ticket emails to customers whose qr_code was generated by the old
// Replit system. Old format: TKT-XXXXXX-ABC-001-XXXXXX (6-char order segment).
// New format: TKT-XXXXXXXX-001-XXXXXXXX (8-char order segment, no type abbrev).
// The customer's original email encoded a different code than what's now in DB,
// so their QR won't scan. This resends with the correct DB qr_code.

export async function POST(req: NextRequest) {
  if (!verifyAdminToken(req)) return unauthorizedResponse();

  const { event_slug } = await req.json();
  if (!event_slug) return NextResponse.json({ error: "event_slug required" }, { status: 400 });

  const db = supabaseAdmin as any;

  // Find all old-format ticket instances for this event
  // Old format matches: TKT-{6chars}-{3chars}-{num}-{6chars}
  const { data: oldTickets, error } = await db
    .from("ticket_instances")
    .select(`
      id, qr_code, ticket_number, ticket_type, holder_name, order_id,
      ticket_orders(id, order_number, customer_email, customer_name, quantity, event_slug, event_city, total, ticket_type)
    `)
    .ilike("event_slug", `%${event_slug}%`)
    .like("qr_code", "TKT-______-___-%");

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  if (!oldTickets?.length) return NextResponse.json({ sent: 0, message: "No old-format tickets found" });

  // Group by order so we send one email per order (with all tickets)
  const byOrder = new Map<string, { order: any; tickets: any[] }>();
  for (const ti of oldTickets) {
    const order = ti.ticket_orders;
    if (!order) continue;
    if (!byOrder.has(ti.order_id)) byOrder.set(ti.order_id, { order, tickets: [] });
    byOrder.get(ti.order_id)!.tickets.push(ti);
  }

  const event = getEvent(event_slug);
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || "https://www.tequilafestusa.com";
  let sent = 0;
  let failed = 0;
  const errors: string[] = [];

  for (const { order, tickets } of byOrder.values()) {
    tickets.sort((a: any, b: any) => a.ticket_number - b.ticket_number);
    const firstName = (order.customer_name || "Guest").split(" ")[0];
    const ticketLabel = TICKET_LABELS[order.ticket_type as keyof typeof TICKET_LABELS] || order.ticket_type || "All Inclusive";

    const ticketInstances = tickets.map((t: any) => ({
      qrCode: t.qr_code,
      ticketNumber: t.ticket_number || 1,
      totalInOrder: order.quantity,
      holderName: t.holder_name || order.customer_name,
      ticketType: ticketLabel,
    }));

    try {
      await resend.emails.send({
        from: FROM_EMAIL,
        to: order.customer_email,
        subject: `🎟️ Updated QR Tickets — Tequila Fest ${order.event_city || ""} ${order.order_number}`,
        html: qrTicketHtml({
          firstName,
          eventCity: order.event_city || "USA",
          eventDate: event?.date || "2026",
          eventTime: event?.time || "3:00 PM – 9:00 PM",
          eventVenue: event ? `${event.venue}, ${event.venueDetail}` : "",
          orderNumber: order.order_number,
          tickets: ticketInstances,
          appUrl,
          total: parseFloat(order.total),
          ticketType: ticketLabel,
          quantity: order.quantity,
        }),
      });
      sent++;
      // Small delay to avoid Resend rate limits
      await new Promise(r => setTimeout(r, 150));
    } catch (e: any) {
      failed++;
      errors.push(`${order.customer_email}: ${e.message}`);
    }
  }

  return NextResponse.json({ sent, failed, errors });
}
